# Generated by Django 5.2.5 on 2025-08-16 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accesorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("direccion", models.TextField(blank=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reparacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orden_numero",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("imei", models.CharField(max_length=15, unique=True)),
                ("falla_reportada", models.TextField()),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Recibido", "Recibido"),
                            ("En proceso", "En Proceso"),
                            ("Listo para entregar", "Listo para Entregar"),
                            ("Entregado", "Entregado"),
                        ],
                        default="Recibido",
                        max_length=50,
                    ),
                ),
                ("tecnico_asignado", models.CharField(blank=True, max_length=100)),
                (
                    "costo_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("fecha_recepcion", models.DateTimeField(auto_now_add=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reparaciones",
                        to="gestion.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VentaAccesorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_venta", models.DateTimeField(auto_now_add=True)),
                (
                    "accesorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.accesorio",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras",
                        to="gestion.cliente",
                    ),
                ),
            ],
        ),
    ]
